
name: Sincronizar Notas con S3

on:
   push:
    branches:
      - main
   workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Obtener notas de S3
        uses: actions/checkout@v4
        
      - name: Obtener credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Comprobar Identidad
        run: aws sts get-caller-identity
       
      # Runs a set of commands using the runners shell
      - name: Sincronizar notas con S3
        run: |
            aws s3 sync . "s3://${{ vars.S3_BUCKET }}/bigtech/" \
              --delete \
              --exclude ".git/*" \
              --exclude ".github/*" \
              --exclude ".obsidian/*"
